### ISSUE TITLE
TypeScript declarations

### ISSUE THREAD

**Issue by P4sca1** [breejs/later#4]
@niftylettuce Are you interested in hosting the typescript declarations in this repository or even convert this project to typescript?
There already exist type declarations under @types/later which in case you don't want to copy them to this repository, would need to be published under @types/breejs__later by doing a pull request to DefinitelyTyped. For users it might be easier to ship the declarations directly with this package.

Also I just saw that you combined all the files into a single huge index.js file which IMO makes it harder to read the code. Could you clarify why this change was made?

Thanks for maintaining later! ❤️

**Comment by niftylettuce** [comment]
Hey thanks for filing this, unfortunately I don't support TypeScript on any of my projects.  It's bad for open source and development in general.  I combined them and fixed the tests.  The code was already hard to read and had several bugs and I had limited time to do this so that was the best approach.

**Comment by delewis13** [comment]
Curious as to why not leverage the work already done for @types/later? 

Seems an easy fix for a relatively large win for any typescript users who want to use this library.

**Comment by niftylettuce** [comment]
Like I said I strictly don't support TypeScript.  It's really bad for the open source JavaScript community.
